name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

# Automatically cancel any previous runs that are still in progress when a new push is made.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Enables automatic caching of the Flutter SDK

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build Web
        # The base-href is set to '/' for a User Pages site (e.g., username.github.io).
        # If this will be a project site (username.github.io/portfolio_web/), change the base-href to '/portfolio_web/'.
        run: flutter build web --release --base-href "/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
